### PR TITLE
[CCAP-510] Updated Homepage Copy

### PR DESCRIPTION
**Pull request by enyia21**
#### 🔗 Jira ticket
[CCAP-510]

#### ✍️ Description
Updated Copy for homepage screen

#### 📷 Design reference
[Figma](https://www.figma.com/design/1oRFY7p6tdGogBJk7Ugle8/IL-CCAP-Families-Application?node-id=6926-19083&t=qyTkC9axxWR94eMt-4)

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

[CCAP-510]: https://codeforamerica.atlassian.net/browse/CCAP-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by cram-cfa** [comment]
Is this ready for review? (There's no label on it, so just confirming)

**Review by cram-cfa — APPROVED** [review]
For what it's worth, in the future... if we know the work is just updating text that's in Transifex, kick the ticket back to Carlie or Carl and have them just do the changes in Transifex.

But anyway, for this one since you already did it... @enyia21 Have you added the Spanish translations for this to Transifex yet? If not, please make sure you do that, and then merge all this in and send it over to Acceptance IMO! 😄

**Comment by enyia21** [comment]
@cram-cfa.  I have not added the changes to transifex.  I didn't realize that we were adding the translations to transifex when copy changes were being made

**Comment by cram-cfa** [comment]
> @cram-cfa. I have not added the changes to transifex. I didn't realize that we were adding the translations to transifex when copy changes were being made

Yeah, we're supposed to be adding the Spanish translations in the PR branch that is opened in Transifex. That's what we agreed upon with Carl and Carlie. From this "branch" in Transifex:

Screenshot 2024-12-17 at 9 56 09 AM

https://app.transifex.com/code-for-america-1/snil-il-get-childcare/translate/#es/e7ba367327a50c66a9c93f16086f51d3/566791769?q=translated%3Ano should be all you need to update.

**Pull request merged**
