### PR TITLE
Upgrade FFL to indicate required inputs

### PR DESCRIPTION
**Pull request by analoo**
#### 🔗 Jira ticket
[CCAP-70](https://codeforamerica.atlassian.net/browse/CCAP-70)

#### ✍️ Description
- Upgrade to version of FFL (1.3.7) that has the required upgrade
- In this document: [Here](https://docs.google.com/spreadsheets/d/1X5TlBFpIbxkTbDzrCfqNv8bhCqM3tnllo1NFVqITHxo/edit?gid=187665420#gid=187665420)
   - Note which fields are required
   - Note the asterisks that have been removed (To be removed in transifex on the english strings are merged)
   - Note which fields have the required value
- Reorganized the input page to be organized by screen and screen order

#### ✅ Completion tasks

- [ ] Added relevant tests
- [ ] Meets acceptance criteria

[CCAP-70]: https://codeforamerica.atlassian.net/browse/CCAP-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by coltborg** [comment]
@analoo Can you try to update the form flow to `1.3.7` and see if things still work as you expect them too?

**Comment by analoo** [comment]
Screenshot 2024-07-31 at 11 35 28 AM
1.3.7 is successfully built! @coltborg

**Review by cram-cfa — COMMENTED** [review]
@analoo one question: are there changes to `messages_es.properties` that need to be done as well?

**Comment by analoo** [comment]
> @analoo one question: are there changes to `messages_es.properties` that need to be done as well?

Yes but changes to the messages_es.properties are done in transifex, not in the messages_es.properties file.

**Comment by cram-cfa** [comment]
> > @analoo one question: are there changes to `messages_es.properties` that need to be done as well?
> 
> Yes but changes to the messages_es.properties are done in transifex, not in the messages_es.properties file.

Ok cool, that's what I suspected but wasn't positive!

**Review by cram-cfa — APPROVED** [review]

**Pull request merged**
